title: Weave WPF Toolkit Docs
description: Weave WPF Toolkit documentation site.

remote_theme: just-the-docs/just-the-docs

url: https://pages.git.autodesk.com/snelle/my-app

aux_links:
  Git Repository: https://git.autodesk.com/snelle/my-app

logo: "/weave-wpf-logo.png"
favicon_ico: "/favicon.ico"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false